export interface ReadyStyle {
  id: string
  name: string
  category: string
  preview: string
}

export const styleCategories: Record<string, string> = {
  gaming: "Gaming",
  cool: "Cool",
  cute: "Cute",
  dark: "Dark",
  royal: "Royal",
  nature: "Nature",
  tech: "Tech",
  sport: "Sport",
}

// 200+ hazır stil şablonları
export const readyStyles: ReadyStyle[] = [
  // Gaming Category (30 styles)
  { id: "g1", category: "gaming", name: "Pro Gamer", preview: "『ᴘʀᴏ』" },
  { id: "g2", category: "gaming", name: "Legend", preview: "⚡ʟᴇɢᴇɴᴅ⚡" },
  { id: "g3", category: "gaming", name: "King", preview: "👑ᴋɪɴɢ👑" },
  { id: "g4", category: "gaming", name: "Warrior", preview: "⚔️ᴡᴀʀʀɪᴏʀ⚔️" },
  { id: "g5", category: "gaming", name: "Ninja", preview: "🥷ɴɪɴᴊᴀ🥷" },
  { id: "g6", category: "gaming", name: "Sniper", preview: "🎯sɴɪᴘᴇʀ🎯" },
  { id: "g7", category: "gaming", name: "Beast", preview: "🦁ʙᴇᴀsᴛ🦁" },
  { id: "g8", category: "gaming", name: "Dragon", preview: "🐉ᴅʀᴀɢᴏɴ🐉" },
  { id: "g9", category: "gaming", name: "Phoenix", preview: "🔥ᴘʜᴏᴇɴɪx🔥" },
  { id: "g10", category: "gaming", name: "Shadow", preview: "🌑sʜᴀᴅᴏᴡ🌑" },
  { id: "g11", category: "gaming", name: "Ghost", preview: "👻ɢʜᴏsᴛ👻" },
  { id: "g12", category: "gaming", name: "Demon", preview: "😈ᴅᴇᴍᴏɴ😈" },
  { id: "g13", category: "gaming", name: "Angel", preview: "😇ᴀɴɢᴇʟ😇" },
  { id: "g14", category: "gaming", name: "Titan", preview: "⚡ᴛɪᴛᴀɴ⚡" },
  { id: "g15", category: "gaming", name: "Venom", preview: "☠️ᴠᴇɴᴏᴍ☠️" },
  { id: "g16", category: "gaming", name: "Savage", preview: "🔪sᴀᴠᴀɢᴇ🔪" },
  { id: "g17", category: "gaming", name: "Hunter", preview: "🏹ʜᴜɴᴛᴇʀ🏹" },
  { id: "g18", category: "gaming", name: "Killer", preview: "💀ᴋɪʟʟᴇʀ💀" },
  { id: "g19", category: "gaming", name: "Master", preview: "🎮ᴍᴀsᴛᴇʀ🎮" },
  { id: "g20", category: "gaming", name: "Champion", preview: "🏆ᴄʜᴀᴍᴘɪᴏɴ🏆" },
  { id: "g21", category: "gaming", name: "Elite", preview: "⭐ᴇʟɪᴛᴇ⭐" },
  { id: "g22", category: "gaming", name: "Ace", preview: "🃏ᴀᴄᴇ🃏" },
  { id: "g23", category: "gaming", name: "Blade", preview: "⚔️ʙʟᴀᴅᴇ⚔️" },
  { id: "g24", category: "gaming", name: "Storm", preview: "⛈️sᴛᴏʀᴍ⛈️" },
  { id: "g25", category: "gaming", name: "Thunder", preview: "⚡ᴛʜᴜɴᴅᴇʀ⚡" },
  { id: "g26", category: "gaming", name: "Frost", preview: "❄️ғʀᴏsᴛ❄️" },
  { id: "g27", category: "gaming", name: "Blaze", preview: "🔥ʙʟᴀᴢᴇ🔥" },
  { id: "g28", category: "gaming", name: "Viper", preview: "🐍ᴠɪᴘᴇʀ🐍" },
  { id: "g29", category: "gaming", name: "Reaper", preview: "💀ʀᴇᴀᴘᴇʀ💀" },
  { id: "g30", category: "gaming", name: "Phantom", preview: "👤ᴘʜᴀɴᴛᴏᴍ👤" },

  // Cool Category (30 styles)
  { id: "c1", category: "cool", name: "Stylish", preview: "『sᴛʏʟɪsʜ』" },
  { id: "c2", category: "cool", name: "Unique", preview: "✨ᴜɴɪǫᴜᴇ✨" },
  { id: "c3", category: "cool", name: "Awesome", preview: "⚡ᴀᴡᴇsᴏᴍᴇ⚡" },
  { id: "c4", category: "cool", name: "Epic", preview: "🌟ᴇᴘɪᴄ🌟" },
  { id: "c5", category: "cool", name: "Legendary", preview: "👑ʟᴇɢᴇɴᴅᴀʀʏ👑" },
  { id: "c6", category: "cool", name: "Supreme", preview: "💎sᴜᴘʀᴇᴍᴇ💎" },
  { id: "c7", category: "cool", name: "Premium", preview: "⭐ᴘʀᴇᴍɪᴜᴍ⭐" },
  { id: "c8", category: "cool", name: "Exclusive", preview: "🔥ᴇxᴄʟᴜsɪᴠᴇ🔥" },
  { id: "c9", category: "cool", name: "Limited", preview: "💫ʟɪᴍɪᴛᴇᴅ💫" },
  { id: "c10", category: "cool", name: "Rare", preview: "💎ʀᴀʀᴇ💎" },
  { id: "c11", category: "cool", name: "Special", preview: "✨sᴘᴇᴄɪᴀʟ✨" },
  { id: "c12", category: "cool", name: "VIP", preview: "👑ᴠɪᴘ👑" },
  { id: "c13", category: "cool", name: "Boss", preview: "😎ʙᴏss😎" },
  { id: "c14", category: "cool", name: "Chief", preview: "🎯ᴄʜɪᴇғ🎯" },
  { id: "c15", category: "cool", name: "Captain", preview: "⚓ᴄᴀᴘᴛᴀɪɴ⚓" },
  { id: "c16", category: "cool", name: "Leader", preview: "🌟ʟᴇᴀᴅᴇʀ🌟" },
  { id: "c17", category: "cool", name: "Alpha", preview: "🐺ᴀʟᴘʜᴀ🐺" },
  { id: "c18", category: "cool", name: "Sigma", preview: "💪sɪɢᴍᴀ💪" },
  { id: "c19", category: "cool", name: "Omega", preview: "Ω ᴏᴍᴇɢᴀ Ω" },
  { id: "c20", category: "cool", name: "Nova", preview: "⭐ɴᴏᴠᴀ⭐" },
  { id: "c21", category: "cool", name: "Cosmic", preview: "🌌ᴄᴏsᴍɪᴄ🌌" },
  { id: "c22", category: "cool", name: "Stellar", preview: "✨sᴛᴇʟʟᴀʀ✨" },
  { id: "c23", category: "cool", name: "Quantum", preview: "⚛️ǫᴜᴀɴᴛᴜᴍ⚛️" },
  { id: "c24", category: "cool", name: "Neon", preview: "💡ɴᴇᴏɴ💡" },
  { id: "c25", category: "cool", name: "Cyber", preview: "🤖ᴄʏʙᴇʀ🤖" },
  { id: "c26", category: "cool", name: "Matrix", preview: "💻ᴍᴀᴛʀɪx💻" },
  { id: "c27", category: "cool", name: "Digital", preview: "📱ᴅɪɢɪᴛᴀʟ📱" },
  { id: "c28", category: "cool", name: "Virtual", preview: "🎮ᴠɪʀᴛᴜᴀʟ🎮" },
  { id: "c29", category: "cool", name: "Pixel", preview: "🎨ᴘɪxᴇʟ🎨" },
  { id: "c30", category: "cool", name: "Retro", preview: "📼ʀᴇᴛʀᴏ📼" },

  // Cute Category (30 styles)
  { id: "cu1", category: "cute", name: "Kawaii", preview: "🌸ᴋᴀᴡᴀɪɪ🌸" },
  { id: "cu2", category: "cute", name: "Sweet", preview: "🍭sᴡᴇᴇᴛ🍭" },
  { id: "cu3", category: "cute", name: "Lovely", preview: "💕ʟᴏᴠᴇʟʏ💕" },
  { id: "cu4", category: "cute", name: "Angel", preview: "👼ᴀɴɢᴇʟ👼" },
  { id: "cu5", category: "cute", name: "Princess", preview: "👸ᴘʀɪɴᴄᴇss👸" },
  { id: "cu6", category: "cute", name: "Queen", preview: "👑ǫᴜᴇᴇɴ👑" },
  { id: "cu7", category: "cute", name: "Fairy", preview: "🧚ғᴀɪʀʏ🧚" },
  { id: "cu8", category: "cute", name: "Butterfly", preview: "🦋ʙᴜᴛᴛᴇʀғʟʏ🦋" },
  { id: "cu9", category: "cute", name: "Flower", preview: "🌺ғʟᴏᴡᴇʀ🌺" },
  { id: "cu10", category: "cute", name: "Cherry", preview: "🍒ᴄʜᴇʀʀʏ🍒" },
  { id: "cu11", category: "cute", name: "Peach", preview: "🍑ᴘᴇᴀᴄʜ🍑" },
  { id: "cu12", category: "cute", name: "Candy", preview: "🍬ᴄᴀɴᴅʏ🍬" },
  { id: "cu13", category: "cute", name: "Cookie", preview: "🍪ᴄᴏᴏᴋɪᴇ🍪" },
  { id: "cu14", category: "cute", name: "Cupcake", preview: "🧁ᴄᴜᴘᴄᴀᴋᴇ🧁" },
  { id: "cu15", category: "cute", name: "Honey", preview: "🍯ʜᴏɴᴇʏ🍯" },
  { id: "cu16", category: "cute", name: "Sugar", preview: "🍰sᴜɢᴀʀ🍰" },
  { id: "cu17", category: "cute", name: "Bunny", preview: "🐰ʙᴜɴɴʏ🐰" },
  { id: "cu18", category: "cute", name: "Kitty", preview: "🐱ᴋɪᴛᴛʏ🐱" },
  { id: "cu19", category: "cute", name: "Puppy", preview: "🐶ᴘᴜᴘᴘʏ🐶" },
  { id: "cu20", category: "cute", name: "Bear", preview: "🐻ʙᴇᴀʀ🐻" },
  { id: "cu21", category: "cute", name: "Panda", preview: "🐼ᴘᴀɴᴅᴀ🐼" },
  { id: "cu22", category: "cute", name: "Koala", preview: "🐨ᴋᴏᴀʟᴀ🐨" },
  { id: "cu23", category: "cute", name: "Unicorn", preview: "🦄ᴜɴɪᴄᴏʀɴ🦄" },
  { id: "cu24", category: "cute", name: "Rainbow", preview: "🌈ʀᴀɪɴʙᴏᴡ🌈" },
  { id: "cu25", category: "cute", name: "Star", preview: "⭐sᴛᴀʀ⭐" },
  { id: "cu26", category: "cute", name: "Moon", preview: "🌙ᴍᴏᴏɴ🌙" },
  { id: "cu27", category: "cute", name: "Cloud", preview: "☁️ᴄʟᴏᴜᴅ☁️" },
  { id: "cu28", category: "cute", name: "Sparkle", preview: "✨sᴘᴀʀᴋʟᴇ✨" },
  { id: "cu29", category: "cute", name: "Glitter", preview: "✨ɢʟɪᴛᴛᴇʀ✨" },
  { id: "cu30", category: "cute", name: "Shine", preview: "💫sʜɪɴᴇ💫" },

  // Dark Category (30 styles)
  { id: "d1", category: "dark", name: "Dark", preview: "🖤ᴅᴀʀᴋ🖤" },
  { id: "d2", category: "dark", name: "Shadow", preview: "🌑sʜᴀᴅᴏᴡ🌑" },
  { id: "d3", category: "dark", name: "Night", preview: "🌃ɴɪɢʜᴛ🌃" },
  { id: "d4", category: "dark", name: "Midnight", preview: "🌌ᴍɪᴅɴɪɢʜᴛ🌌" },
  { id: "d5", category: "dark", name: "Eclipse", preview: "🌑ᴇᴄʟɪᴘsᴇ🌑" },
  { id: "d6", category: "dark", name: "Void", preview: "⚫ᴠᴏɪᴅ⚫" },
  { id: "d7", category: "dark", name: "Abyss", preview: "🕳️ᴀʙʏss🕳️" },
  { id: "d8", category: "dark", name: "Raven", preview: "🦅ʀᴀᴠᴇɴ🦅" },
  { id: "d9", category: "dark", name: "Crow", preview: "🐦‍⬛ᴄʀᴏᴡ🐦‍⬛" },
  { id: "d10", category: "dark", name: "Panther", preview: "🐆ᴘᴀɴᴛʜᴇʀ🐆" },
  { id: "d11", category: "dark", name: "Wolf", preview: "🐺ᴡᴏʟғ🐺" },
  { id: "d12", category: "dark", name: "Vampire", preview: "🧛ᴠᴀᴍᴘɪʀᴇ🧛" },
  { id: "d13", category: "dark", name: "Witch", preview: "🧙ᴡɪᴛᴄʜ🧙" },
  { id: "d14", category: "dark", name: "Warlock", preview: "🧙‍♂️ᴡᴀʀʟᴏᴄᴋ🧙‍♂️" },
  { id: "d15", category: "dark", name: "Necro", preview: "💀ɴᴇᴄʀᴏ💀" },
  { id: "d16", category: "dark", name: "Skull", preview: "☠️sᴋᴜʟʟ☠️" },
  { id: "d17", category: "dark", name: "Bone", preview: "🦴ʙᴏɴᴇ🦴" },
  { id: "d18", category: "dark", name: "Grave", preview: "⚰️ɢʀᴀᴠᴇ⚰️" },
  { id: "d19", category: "dark", name: "Tomb", preview: "🪦ᴛᴏᴍʙ🪦" },
  { id: "d20", category: "dark", name: "Curse", preview: "🔮ᴄᴜʀsᴇ🔮" },
  { id: "d21", category: "dark", name: "Hex", preview: "🔯ʜᴇx🔯" },
  { id: "d22", category: "dark", name: "Spell", preview: "✨sᴘᴇʟʟ✨" },
  { id: "d23", category: "dark", name: "Magic", preview: "🪄ᴍᴀɢɪᴄ🪄" },
  { id: "d24", category: "dark", name: "Mystery", preview: "🔮ᴍʏsᴛᴇʀʏ🔮" },
  { id: "d25", category: "dark", name: "Enigma", preview: "❓ᴇɴɪɢᴍᴀ❓" },
  { id: "d26", category: "dark", name: "Riddle", preview: "🎭ʀɪᴅᴅʟᴇ🎭" },
  { id: "d27", category: "dark", name: "Secret", preview: "🤫sᴇᴄʀᴇᴛ🤫" },
  { id: "d28", category: "dark", name: "Hidden", preview: "🕵️ʜɪᴅᴅᴇɴ🕵️" },
  { id: "d29", category: "dark", name: "Silent", preview: "🤐sɪʟᴇɴᴛ🤐" },
  { id: "d30", category: "dark", name: "Quiet", preview: "🔇ǫᴜɪᴇᴛ🔇" },

  // Royal Category (30 styles)
  { id: "r1", category: "royal", name: "Royal", preview: "👑ʀᴏʏᴀʟ👑" },
  { id: "r2", category: "royal", name: "Imperial", preview: "👑ɪᴍᴘᴇʀɪᴀʟ👑" },
  { id: "r3", category: "royal", name: "Majestic", preview: "👑ᴍᴀᴊᴇsᴛɪᴄ👑" },
  { id: "r4", category: "royal", name: "Noble", preview: "🎩ɴᴏʙʟᴇ🎩" },
  { id: "r5", category: "royal", name: "Lord", preview: "🤴ʟᴏʀᴅ🤴" },
  { id: "r6", category: "royal", name: "Lady", preview: "👸ʟᴀᴅʏ👸" },
  { id: "r7", category: "royal", name: "Duke", preview: "🎩ᴅᴜᴋᴇ🎩" },
  { id: "r8", category: "royal", name: "Duchess", preview: "👑ᴅᴜᴄʜᴇss👑" },
  { id: "r9", category: "royal", name: "Prince", preview: "🤴ᴘʀɪɴᴄᴇ🤴" },
  { id: "r10", category: "royal", name: "Emperor", preview: "👑ᴇᴍᴘᴇʀᴏʀ👑" },
  { id: "r11", category: "royal", name: "Empress", preview: "👑ᴇᴍᴘʀᴇss👑" },
  { id: "r12", category: "royal", name: "Monarch", preview: "👑ᴍᴏɴᴀʀᴄʜ👑" },
  { id: "r13", category: "royal", name: "Sovereign", preview: "👑sᴏᴠᴇʀᴇɪɢɴ👑" },
  { id: "r14", category: "royal", name: "Regent", preview: "👑ʀᴇɢᴇɴᴛ👑" },
  { id: "r15", category: "royal", name: "Crown", preview: "👑ᴄʀᴏᴡɴ👑" },
  { id: "r16", category: "royal", name: "Throne", preview: "🪑ᴛʜʀᴏɴᴇ🪑" },
  { id: "r17", category: "royal", name: "Palace", preview: "🏰ᴘᴀʟᴀᴄᴇ🏰" },
  { id: "r18", category: "royal", name: "Castle", preview: "🏰ᴄᴀsᴛʟᴇ🏰" },
  { id: "r19", category: "royal", name: "Kingdom", preview: "🏰ᴋɪɴɢᴅᴏᴍ🏰" },
  { id: "r20", category: "royal", name: "Empire", preview: "🏛️ᴇᴍᴘɪʀᴇ🏛️" },
  { id: "r21", category: "royal", name: "Dynasty", preview: "👑ᴅʏɴᴀsᴛʏ👑" },
  { id: "r22", category: "royal", name: "Legacy", preview: "📜ʟᴇɢᴀᴄʏ📜" },
  { id: "r23", category: "royal", name: "Heritage", preview: "🏛️ʜᴇʀɪᴛᴀɢᴇ🏛️" },
  { id: "r24", category: "royal", name: "Prestige", preview: "💎ᴘʀᴇsᴛɪɢᴇ💎" },
  { id: "r25", category: "royal", name: "Elegance", preview: "✨ᴇʟᴇɢᴀɴᴄᴇ✨" },
  { id: "r26", category: "royal", name: "Grace", preview: "🌟ɢʀᴀᴄᴇ🌟" },
  { id: "r27", category: "royal", name: "Dignity", preview: "🎩ᴅɪɢɴɪᴛʏ🎩" },
  { id: "r28", category: "royal", name: "Honor", preview: "🏅ʜᴏɴᴏʀ🏅" },
  { id: "r29", category: "royal", name: "Glory", preview: "🌟ɢʟᴏʀʏ🌟" },
  { id: "r30", category: "royal", name: "Triumph", preview: "🏆ᴛʀɪᴜᴍᴘʜ🏆" },

  // Nature Category (30 styles)
  { id: "n1", category: "nature", name: "Nature", preview: "🌿ɴᴀᴛᴜʀᴇ🌿" },
  { id: "n2", category: "nature", name: "Forest", preview: "🌲ғᴏʀᴇsᴛ🌲" },
  { id: "n3", category: "nature", name: "Ocean", preview: "🌊ᴏᴄᴇᴀɴ🌊" },
  { id: "n4", category: "nature", name: "Mountain", preview: "⛰️ᴍᴏᴜɴᴛᴀɪɴ⛰️" },
  { id: "n5", category: "nature", name: "River", preview: "🏞️ʀɪᴠᴇʀ🏞️" },
  { id: "n6", category: "nature", name: "Lake", preview: "🏞️ʟᴀᴋᴇ🏞️" },
  { id: "n7", category: "nature", name: "Sky", preview: "☁️sᴋʏ☁️" },
  { id: "n8", category: "nature", name: "Sun", preview: "☀️sᴜɴ☀️" },
  { id: "n9", category: "nature", name: "Wind", preview: "💨ᴡɪɴᴅ💨" },
  { id: "n10", category: "nature", name: "Rain", preview: "🌧️ʀᴀɪɴ🌧️" },
  { id: "n11", category: "nature", name: "Snow", preview: "❄️sɴᴏᴡ❄️" },
  { id: "n12", category: "nature", name: "Ice", preview: "🧊ɪᴄᴇ🧊" },
  { id: "n13", category: "nature", name: "Fire", preview: "🔥ғɪʀᴇ🔥" },
  { id: "n14", category: "nature", name: "Earth", preview: "🌍ᴇᴀʀᴛʜ🌍" },
  { id: "n15", category: "nature", name: "Stone", preview: "🪨sᴛᴏɴᴇ🪨" },
  { id: "n16", category: "nature", name: "Crystal", preview: "💎ᴄʀʏsᴛᴀʟ💎" },
  { id: "n17", category: "nature", name: "Leaf", preview: "🍃ʟᴇᴀғ🍃" },
  { id: "n18", category: "nature", name: "Tree", preview: "🌳ᴛʀᴇᴇ🌳" },
  { id: "n19", category: "nature", name: "Rose", preview: "🌹ʀᴏsᴇ🌹" },
  { id: "n20", category: "nature", name: "Lotus", preview: "🪷ʟᴏᴛᴜs🪷" },
  { id: "n21", category: "nature", name: "Sakura", preview: "🌸sᴀᴋᴜʀᴀ🌸" },
  { id: "n22", category: "nature", name: "Blossom", preview: "🌺ʙʟᴏssᴏᴍ🌺" },
  { id: "n23", category: "nature", name: "Petal", preview: "🌸ᴘᴇᴛᴀʟ🌸" },
  { id: "n24", category: "nature", name: "Garden", preview: "🏡ɢᴀʀᴅᴇɴ🏡" },
  { id: "n25", category: "nature", name: "Meadow", preview: "🌾ᴍᴇᴀᴅᴏᴡ🌾" },
  { id: "n26", category: "nature", name: "Valley", preview: "🏞️ᴠᴀʟʟᴇʏ🏞️" },
  { id: "n27", category: "nature", name: "Canyon", preview: "🏜️ᴄᴀɴʏᴏɴ🏜️" },
  { id: "n28", category: "nature", name: "Desert", preview: "🏜️ᴅᴇsᴇʀᴛ🏜️" },
  { id: "n29", category: "nature", name: "Jungle", preview: "🌴ᴊᴜɴɢʟᴇ🌴" },
  { id: "n30", category: "nature", name: "Wild", preview: "🦁ᴡɪʟᴅ🦁" },

  // Tech Category (30 styles)
  { id: "t1", category: "tech", name: "Tech", preview: "💻ᴛᴇᴄʜ💻" },
  { id: "t2", category: "tech", name: "Code", preview: "👨‍💻ᴄᴏᴅᴇ👨‍💻" },
  { id: "t3", category: "tech", name: "Hack", preview: "🔓ʜᴀᴄᴋ🔓" },
  { id: "t4", category: "tech", name: "Binary", preview: "01 ʙɪɴᴀʀʏ 01" },
  { id: "t5", category: "tech", name: "Data", preview: "📊ᴅᴀᴛᴀ📊" },
  { id: "t6", category: "tech", name: "System", preview: "⚙️sʏsᴛᴇᴍ⚙️" },
  { id: "t7", category: "tech", name: "Network", preview: "🌐ɴᴇᴛᴡᴏʀᴋ🌐" },
  { id: "t8", category: "tech", name: "Server", preview: "🖥️sᴇʀᴠᴇʀ🖥️" },
  { id: "t9", category: "tech", name: "Cloud", preview: "☁️ᴄʟᴏᴜᴅ☁️" },
  { id: "t10", category: "tech", name: "AI", preview: "🤖ᴀɪ🤖" },
  { id: "t11", category: "tech", name: "Robot", preview: "🤖ʀᴏʙᴏᴛ🤖" },
  { id: "t12", category: "tech", name: "Android", preview: "🤖ᴀɴᴅʀᴏɪᴅ🤖" },
  { id: "t13", category: "tech", name: "Cyborg", preview: "🦾ᴄʏʙᴏʀɢ🦾" },
  { id: "t14", category: "tech", name: "Mech", preview: "🤖ᴍᴇᴄʜ🤖" },
  { id: "t15", category: "tech", name: "Bot", preview: "🤖ʙᴏᴛ🤖" },
  { id: "t16", category: "tech", name: "Drone", preview: "🚁ᴅʀᴏɴᴇ🚁" },
  { id: "t17", category: "tech", name: "Satellite", preview: "🛰️sᴀᴛᴇʟʟɪᴛᴇ🛰️" },
  { id: "t18", category: "tech", name: "Rocket", preview: "🚀ʀᴏᴄᴋᴇᴛ🚀" },
  { id: "t19", category: "tech", name: "Space", preview: "🌌sᴘᴀᴄᴇ🌌" },
  { id: "t20", category: "tech", name: "Galaxy", preview: "🌌ɢᴀʟᴀxʏ🌌" },
  { id: "t21", category: "tech", name: "Orbit", preview: "🛸ᴏʀʙɪᴛ🛸" },
  { id: "t22", category: "tech", name: "Laser", preview: "🔦ʟᴀsᴇʀ🔦" },
  { id: "t23", category: "tech", name: "Plasma", preview: "⚡ᴘʟᴀsᴍᴀ⚡" },
  { id: "t24", category: "tech", name: "Energy", preview: "⚡ᴇɴᴇʀɢʏ⚡" },
  { id: "t25", category: "tech", name: "Power", preview: "🔋ᴘᴏᴡᴇʀ🔋" },
  { id: "t26", category: "tech", name: "Volt", preview: "⚡ᴠᴏʟᴛ⚡" },
  { id: "t27", category: "tech", name: "Circuit", preview: "🔌ᴄɪʀᴄᴜɪᴛ🔌" },
  { id: "t28", category: "tech", name: "Wire", preview: "🔌ᴡɪʀᴇ🔌" },
  { id: "t29", category: "tech", name: "Signal", preview: "📡sɪɢɴᴀʟ📡" },
  { id: "t30", category: "tech", name: "Frequency", preview: "📻ғʀᴇǫᴜᴇɴᴄʏ📻" },

  // Sport Category (20 styles)
  { id: "s1", category: "sport", name: "Sport", preview: "⚽sᴘᴏʀᴛ⚽" },
  { id: "s2", category: "sport", name: "Football", preview: "⚽ғᴏᴏᴛʙᴀʟʟ⚽" },
  { id: "s3", category: "sport", name: "Basketball", preview: "🏀ʙᴀsᴋᴇᴛʙᴀʟʟ🏀" },
  { id: "s4", category: "sport", name: "Tennis", preview: "🎾ᴛᴇɴɴɪs🎾" },
  { id: "s5", category: "sport", name: "Baseball", preview: "⚾ʙᴀsᴇʙᴀʟʟ⚾" },
  { id: "s6", category: "sport", name: "Volleyball", preview: "🏐ᴠᴏʟʟᴇʏʙᴀʟʟ🏐" },
  { id: "s7", category: "sport", name: "Golf", preview: "⛳ɢᴏʟғ⛳" },
  { id: "s8", category: "sport", name: "Racing", preview: "🏎️ʀᴀᴄɪɴɢ🏎️" },
  { id: "s9", category: "sport", name: "Boxing", preview: "🥊ʙᴏxɪɴɢ🥊" },
  { id: "s10", category: "sport", name: "Fitness", preview: "💪ғɪᴛɴᴇss💪" },
  { id: "s11", category: "sport", name: "Gym", preview: "🏋️ɢʏᴍ🏋️" },
  { id: "s12", category: "sport", name: "Athlete", preview: "🏃ᴀᴛʜʟᴇᴛᴇ🏃" },
  { id: "s13", category: "sport", name: "Runner", preview: "🏃ʀᴜɴɴᴇʀ🏃" },
  { id: "s14", category: "sport", name: "Swimmer", preview: "🏊sᴡɪᴍᴍᴇʀ🏊" },
  { id: "s15", category: "sport", name: "Cyclist", preview: "🚴ᴄʏᴄʟɪsᴛ🚴" },
  { id: "s16", category: "sport", name: "Skater", preview: "⛸️sᴋᴀᴛᴇʀ⛸️" },
  { id: "s17", category: "sport", name: "Surfer", preview: "🏄sᴜʀғᴇʀ🏄" },
  { id: "s18", category: "sport", name: "Climber", preview: "🧗ᴄʟɪᴍʙᴇʀ🧗" },
  { id: "s19", category: "sport", name: "Diver", preview: "🤿ᴅɪᴠᴇʀ🤿" },
  { id: "s20", category: "sport", name: "Skier", preview: "⛷️sᴋɪᴇʀ⛷️" },
]
