export interface ReadyNick {
  id: string
  text: string
  category: string
}

export interface NickCategory {
  id: string
  name: string
  icon: string
  nameEn: string
  nameTr: string
  nameEs: string
  nameFr: string
  nameDe: string
}

export const nickCategories: NickCategory[] = [
  {
    id: "gaming",
    name: "Gaming",
    icon: "🎮",
    nameEn: "Gaming",
    nameTr: "Oyun",
    nameEs: "Juegos",
    nameFr: "Jeux",
    nameDe: "Spiele",
  },
  {
    id: "cool",
    name: "Cool",
    icon: "😎",
    nameEn: "Cool",
    nameTr: "Havalı",
    nameEs: "Genial",
    nameFr: "Cool",
    nameDe: "Cool",
  },
  {
    id: "cute",
    name: "Cute",
    icon: "🌸",
    nameEn: "Cute",
    nameTr: "Sevimli",
    nameEs: "Lindo",
    nameFr: "Mignon",
    nameDe: "Süß",
  },
  {
    id: "dark",
    name: "Dark",
    icon: "🖤",
    nameEn: "Dark",
    nameTr: "Karanlık",
    nameEs: "Oscuro",
    nameFr: "Sombre",
    nameDe: "Dunkel",
  },
  {
    id: "vip",
    name: "VIP",
    icon: "👑",
    nameEn: "VIP",
    nameTr: "VIP",
    nameEs: "VIP",
    nameFr: "VIP",
    nameDe: "VIP",
  },
  {
    id: "aesthetic",
    name: "Aesthetic",
    icon: "✨",
    nameEn: "Aesthetic",
    nameTr: "Estetik",
    nameEs: "Estético",
    nameFr: "Esthétique",
    nameDe: "Ästhetisch",
  },
]

export const readyNicks: ReadyNick[] = [
  // Gaming Category (40 nicks)
  { id: "g1", text: "ᴾᴿᴼ༒GAMER༒", category: "gaming" },
  { id: "g2", text: "꧁༒☬LEGEND☬༒꧂", category: "gaming" },
  { id: "g3", text: "『ᴹᵛᴸ』KILLER", category: "gaming" },
  { id: "g4", text: "༺Leͥgeͣnͫd༻ᴳᵒᵈ", category: "gaming" },
  { id: "g5", text: "꧁༺J꙰O꙰K꙰E꙰R꙰༻꧂", category: "gaming" },
  { id: "g6", text: "『ᴹᴷ』SNIPER", category: "gaming" },
  { id: "g7", text: "༒☬NINJA☬༒", category: "gaming" },
  { id: "g8", text: "꧁༒WARRIOR༒꧂", category: "gaming" },
  { id: "g9", text: "ᴾᴿᴼ༒PLAYER༒", category: "gaming" },
  { id: "g10", text: "『ᴹᴸ』MASTER", category: "gaming" },
  { id: "g11", text: "༺HUNTER༻ᴳᵒᵈ", category: "gaming" },
  { id: "g12", text: "꧁༒SHADOW༒꧂", category: "gaming" },
  { id: "g13", text: "『ᴷᴵᴺᴳ』SLAYER", category: "gaming" },
  { id: "g14", text: "༒☬DEMON☬༒", category: "gaming" },
  { id: "g15", text: "꧁༺PHANTOM༻꧂", category: "gaming" },
  { id: "g16", text: "ᴾᴿᴼ༒BEAST༒", category: "gaming" },
  { id: "g17", text: "『ᴹᵛᴸ』DRAGON", category: "gaming" },
  { id: "g18", text: "༺TITAN༻ᴳᵒᵈ", category: "gaming" },
  { id: "g19", text: "꧁༒GHOST༒꧂", category: "gaming" },
  { id: "g20", text: "༒☬REAPER☬༒", category: "gaming" },
  { id: "g21", text: "『ᴷᴵᴺᴳ』VIPER", category: "gaming" },
  { id: "g22", text: "꧁༺SAVAGE༻꧂", category: "gaming" },
  { id: "g23", text: "ᴾᴿᴼ༒HAWK༒", category: "gaming" },
  { id: "g24", text: "༺STORM༻ᴳᵒᵈ", category: "gaming" },
  { id: "g25", text: "『ᴹᴸ』THUNDER", category: "gaming" },
  { id: "g26", text: "༒☬BLADE☬༒", category: "gaming" },
  { id: "g27", text: "꧁༒FURY༒꧂", category: "gaming" },
  { id: "g28", text: "『ᴹᵛᴸ』PHOENIX", category: "gaming" },
  { id: "g29", text: "༺ALPHA༻ᴳᵒᵈ", category: "gaming" },
  { id: "g30", text: "꧁༺OMEGA༻꧂", category: "gaming" },
  { id: "g31", text: "ᴾᴿᴼ༒WOLF༒", category: "gaming" },
  { id: "g32", text: "༒☬RAVEN☬༒", category: "gaming" },
  { id: "g33", text: "『ᴷᴵᴺᴳ』COBRA", category: "gaming" },
  { id: "g34", text: "꧁༒VENOM༒꧂", category: "gaming" },
  { id: "g35", text: "༺CHAOS༻ᴳᵒᵈ", category: "gaming" },
  { id: "g36", text: "『ᴹᴸ』STRIKER", category: "gaming" },
  { id: "g37", text: "༒☬BLAZE☬༒", category: "gaming" },
  { id: "g38", text: "꧁༺INFERNO༻꧂", category: "gaming" },
  { id: "g39", text: "ᴾᴿᴼ༒APEX༒", category: "gaming" },
  { id: "g40", text: "『ᴹᵛᴸ』ELITE", category: "gaming" },

  // Cool Category (40 nicks)
  { id: "c1", text: "★彡[ᴅᴇᴠɪʟ]彡★", category: "cool" },
  { id: "c2", text: "▄︻デ═一 SNIPER", category: "cool" },
  { id: "c3", text: "『ᴹᴿ』PERFECT", category: "cool" },
  { id: "c4", text: "༺ᴮᴬᴰ༒ᴮᴼᵞ༻", category: "cool" },
  { id: "c5", text: "꧁༺BOSS༻꧂", category: "cool" },
  { id: "c6", text: "★彡[STYLE]彡★", category: "cool" },
  { id: "c7", text: "『ᴹᴿ』COOL", category: "cool" },
  { id: "c8", text: "༺ᴮᴬᴰ༒ɢɪʀʟ༻", category: "cool" },
  { id: "c9", text: "꧁༒ACE༒꧂", category: "cool" },
  { id: "c10", text: "★彡[SWAG]彡★", category: "cool" },
  { id: "c11", text: "『ᴹᴿ』SAVAGE", category: "cool" },
  { id: "c12", text: "༺REBEL༻", category: "cool" },
  { id: "c13", text: "꧁༺DOPE༻꧂", category: "cool" },
  { id: "c14", text: "★彡[CHILL]彡★", category: "cool" },
  { id: "c15", text: "『ᴹᴿ』VIBE", category: "cool" },
  { id: "c16", text: "༺ᴮᴬᴰ༒MOOD༻", category: "cool" },
  { id: "c17", text: "꧁༒FLEX༒꧂", category: "cool" },
  { id: "c18", text: "★彡[WAVE]彡★", category: "cool" },
  { id: "c19", text: "『ᴹᴿ』FRESH", category: "cool" },
  { id: "c20", text: "༺SMOOTH༻", category: "cool" },
  { id: "c21", text: "꧁༺SLICK༻꧂", category: "cool" },
  { id: "c22", text: "★彡[FIRE]彡★", category: "cool" },
  { id: "c23", text: "『ᴹᴿ』BLAZE", category: "cool" },
  { id: "c24", text: "༺ᴮᴬᴰ༒VIBES༻", category: "cool" },
  { id: "c25", text: "꧁༒DRIP༒꧂", category: "cool" },
  { id: "c26", text: "★彡[MOOD]彡★", category: "cool" },
  { id: "c27", text: "『ᴹᴿ』HYPE", category: "cool" },
  { id: "c28", text: "༺ENERGY༻", category: "cool" },
  { id: "c29", text: "꧁༺POWER༻꧂", category: "cool" },
  { id: "c30", text: "★彡[FORCE]彡★", category: "cool" },
  { id: "c31", text: "『ᴹᴿ』IMPACT", category: "cool" },
  { id: "c32", text: "༺ᴮᴬᴰ༒AURA༻", category: "cool" },
  { id: "c33", text: "꧁༒GLOW༒꧂", category: "cool" },
  { id: "c34", text: "★彡[SHINE]彡★", category: "cool" },
  { id: "c35", text: "『ᴹᴿ』SPARK", category: "cool" },
  { id: "c36", text: "༺FLASH༻", category: "cool" },
  { id: "c37", text: "꧁༺BOLT༻꧂", category: "cool" },
  { id: "c38", text: "★彡[STORM]彡★", category: "cool" },
  { id: "c39", text: "『ᴹᴿ』THUNDER", category: "cool" },
  { id: "c40", text: "༺ᴮᴬᴰ༒STRIKE༻", category: "cool" },

  // Cute Category (40 nicks)
  { id: "cu1", text: "♡ᴄᴜᴛɪᴇ♡", category: "cute" },
  { id: "cu2", text: "✿ᴘʀɪɴᴄᴇss✿", category: "cute" },
  { id: "cu3", text: "꧁༺ANGEL༻꧂", category: "cute" },
  { id: "cu4", text: "♡˚₊‧꒰აSWEETა꒱ ‧₊˚♡", category: "cute" },
  { id: "cu5", text: "✧･ﾟ: *✧･ﾟ:*BABY*:･ﾟ✧*:･ﾟ✧", category: "cute" },
  { id: "cu6", text: "♡ᴅᴏʟʟ♡", category: "cute" },
  { id: "cu7", text: "✿ʙᴜᴛᴛᴇʀғʟʏ✿", category: "cute" },
  { id: "cu8", text: "꧁༺FAIRY༻꧂", category: "cute" },
  { id: "cu9", text: "♡˚₊‧꒰აSTARა꒱ ‧₊˚♡", category: "cute" },
  { id: "cu10", text: "✧･ﾟ: *✧･ﾟ:*MOON*:･ﾟ✧*:･ﾟ✧", category: "cute" },
  { id: "cu11", text: "♡ᴘᴇᴀᴄʜ♡", category: "cute" },
  { id: "cu12", text: "✿ʙʟᴏssᴏᴍ✿", category: "cute" },
  { id: "cu13", text: "꧁༺ROSE༻꧂", category: "cute" },
  { id: "cu14", text: "♡˚₊‧꒰აPETALა꒱ ‧₊˚♡", category: "cute" },
  { id: "cu15", text: "✧･ﾟ: *✧･ﾟ:*HONEY*:･ﾟ✧*:･ﾟ✧", category: "cute" },
  { id: "cu16", text: "♡ᴄᴀɴᴅʏ♡", category: "cute" },
  { id: "cu17", text: "✿sᴜɢᴀʀ✿", category: "cute" },
  { id: "cu18", text: "꧁༺CHERRY༻꧂", category: "cute" },
  { id: "cu19", text: "♡˚₊‧꒰აBERRYა꒱ ‧₊˚♡", category: "cute" },
  { id: "cu20", text: "✧･ﾟ: *✧･ﾟ:*DREAM*:･ﾟ✧*:･ﾟ✧", category: "cute" },
  { id: "cu21", text: "♡ᴄʟᴏᴜᴅ♡", category: "cute" },
  { id: "cu22", text: "✿sᴋʏ✿", category: "cute" },
  { id: "cu23", text: "꧁༺HEAVEN༻꧂", category: "cute" },
  { id: "cu24", text: "♡˚₊‧꒰აGLOWა꒱ ‧₊˚♡", category: "cute" },
  { id: "cu25", text: "✧･ﾟ: *✧･ﾟ:*SHINE*:･ﾟ✧*:･ﾟ✧", category: "cute" },
  { id: "cu26", text: "♡sᴘᴀʀᴋʟᴇ♡", category: "cute" },
  { id: "cu27", text: "✿ɢʟɪᴛᴛᴇʀ✿", category: "cute" },
  { id: "cu28", text: "꧁༺MAGIC༻꧂", category: "cute" },
  { id: "cu29", text: "♡˚₊‧꒰აWISHა꒱ ‧₊˚♡", category: "cute" },
  { id: "cu30", text: "✧･ﾟ: *✧･ﾟ:*HOPE*:･ﾟ✧*:･ﾟ✧", category: "cute" },
  { id: "cu31", text: "♡ᴊᴏʏ♡", category: "cute" },
  { id: "cu32", text: "✿ʙʟɪss✿", category: "cute" },
  { id: "cu33", text: "꧁༺SMILE༻꧂", category: "cute" },
  { id: "cu34", text: "♡˚₊‧꒰აHAPPYა꒱ ‧₊˚♡", category: "cute" },
  { id: "cu35", text: "✧･ﾟ: *✧･ﾟ:*LOVE*:･ﾟ✧*:･ﾟ✧", category: "cute" },
  { id: "cu36", text: "♡ʜᴇᴀʀᴛ♡", category: "cute" },
  { id: "cu37", text: "✿ᴋɪss✿", category: "cute" },
  { id: "cu38", text: "꧁༺HUG༻꧂", category: "cute" },
  { id: "cu39", text: "♡˚₊‧꒰აCUDDLEა꒱ ‧₊˚♡", category: "cute" },
  { id: "cu40", text: "✧･ﾟ: *✧･ﾟ:*SOFT*:･ﾟ✧*:･ﾟ✧", category: "cute" },

  // Dark Category (40 nicks)
  { id: "d1", text: "꧁༒☬DEATH☬༒꧂", category: "dark" },
  { id: "d2", text: "༺ᴅᴀʀᴋ༒ᴀɴɢᴇʟ༻", category: "dark" },
  { id: "d3", text: "『ᴰᴱᴹᴼᴺ』SOUL", category: "dark" },
  { id: "d4", text: "༒☬EVIL☬༒", category: "dark" },
  { id: "d5", text: "꧁༺NIGHTMARE༻꧂", category: "dark" },
  { id: "d6", text: "༺ᴅᴀʀᴋ༒ᴋɴɪɢʜᴛ༻", category: "dark" },
  { id: "d7", text: "『ᴰᴱᴹᴼᴺ』BLOOD", category: "dark" },
  { id: "d8", text: "༒☬SHADOW☬༒", category: "dark" },
  { id: "d9", text: "꧁༺VOID༻꧂", category: "dark" },
  { id: "d10", text: "༺ᴅᴀʀᴋ༒ʟᴏʀᴅ༻", category: "dark" },
  { id: "d11", text: "『ᴰᴱᴹᴼᴺ』CURSE", category: "dark" },
  { id: "d12", text: "༒☬RAVEN☬༒", category: "dark" },
  { id: "d13", text: "꧁༺ABYSS༻꧂", category: "dark" },
  { id: "d14", text: "༺ᴅᴀʀᴋ༒ᴍᴀɢᴇ༻", category: "dark" },
  { id: "d15", text: "『ᴰᴱᴹᴼᴺ』WITCH", category: "dark" },
  { id: "d16", text: "༒☬VENOM☬༒", category: "dark" },
  { id: "d17", text: "꧁༺POISON༻꧂", category: "dark" },
  { id: "d18", text: "༺ᴅᴀʀᴋ༒ᴡᴏʟғ༻", category: "dark" },
  { id: "d19", text: "『ᴰᴱᴹᴼᴺ』FANG", category: "dark" },
  { id: "d20", text: "༒☬CLAW☬༒", category: "dark" },
  { id: "d21", text: "꧁༺BEAST༻꧂", category: "dark" },
  { id: "d22", text: "༺ᴅᴀʀᴋ༒ʜᴜɴᴛᴇʀ༻", category: "dark" },
  { id: "d23", text: "『ᴰᴱᴹᴼᴺ』SLAYER", category: "dark" },
  { id: "d24", text: "༒☬REAPER☬༒", category: "dark" },
  { id: "d25", text: "꧁༺GRAVE༻꧂", category: "dark" },
  { id: "d26", text: "༺ᴅᴀʀᴋ༒sᴘɪʀɪᴛ༻", category: "dark" },
  { id: "d27", text: "『ᴰᴱᴹᴼᴺ』GHOST", category: "dark" },
  { id: "d28", text: "༒☬PHANTOM☬༒", category: "dark" },
  { id: "d29", text: "꧁༺WRAITH༻꧂", category: "dark" },
  { id: "d30", text: "༺ᴅᴀʀᴋ༒ᴍᴏᴏɴ༻", category: "dark" },
  { id: "d31", text: "『ᴰᴱᴹᴼᴺ』ECLIPSE", category: "dark" },
  { id: "d32", text: "༒☬MIDNIGHT☬༒", category: "dark" },
  { id: "d33", text: "꧁༺DUSK༻꧂", category: "dark" },
  { id: "d34", text: "༺ᴅᴀʀᴋ༒sᴛᴏʀᴍ༻", category: "dark" },
  { id: "d35", text: "『ᴰᴱᴹᴼᴺ』CHAOS", category: "dark" },
  { id: "d36", text: "༒☬FURY☬༒", category: "dark" },
  { id: "d37", text: "꧁༺RAGE༻꧂", category: "dark" },
  { id: "d38", text: "༺ᴅᴀʀᴋ༒ғɪʀᴇ༻", category: "dark" },
  { id: "d39", text: "『ᴰᴱᴹᴼᴺ』INFERNO", category: "dark" },
  { id: "d40", text: "༒☬BLAZE☬༒", category: "dark" },

  // VIP Category (40 nicks)
  { id: "v1", text: "👑KING👑", category: "vip" },
  { id: "v2", text: "♛QUEEN♛", category: "vip" },
  { id: "v3", text: "『ᴷᴵᴺᴳ』ROYAL", category: "vip" },
  { id: "v4", text: "༺EMPEROR༻", category: "vip" },
  { id: "v5", text: "꧁༺EMPRESS༻꧂", category: "vip" },
  { id: "v6", text: "👑PRINCE👑", category: "vip" },
  { id: "v7", text: "♛PRINCESS♛", category: "vip" },
  { id: "v8", text: "『ᴷᴵᴺᴳ』CROWN", category: "vip" },
  { id: "v9", text: "༺THRONE༻", category: "vip" },
  { id: "v10", text: "꧁༺MAJESTY༻꧂", category: "vip" },
  { id: "v11", text: "👑LORD👑", category: "vip" },
  { id: "v12", text: "♛LADY♛", category: "vip" },
  { id: "v13", text: "『ᴷᴵᴺᴳ』NOBLE", category: "vip" },
  { id: "v14", text: "༺DUKE༻", category: "vip" },
  { id: "v15", text: "꧁༺DUCHESS༻꧂", category: "vip" },
  { id: "v16", text: "👑ELITE👑", category: "vip" },
  { id: "v17", text: "♛LUXURY♛", category: "vip" },
  { id: "v18", text: "『ᴷᴵᴺᴳ』PREMIUM", category: "vip" },
  { id: "v19", text: "༺DIAMOND༻", category: "vip" },
  { id: "v20", text: "꧁༺GOLD༻꧂", category: "vip" },
  { id: "v21", text: "👑PLATINUM👑", category: "vip" },
  { id: "v22", text: "♛SILVER♛", category: "vip" },
  { id: "v23", text: "『ᴷᴵᴺᴳ』CRYSTAL", category: "vip" },
  { id: "v24", text: "༺PEARL༻", category: "vip" },
  { id: "v25", text: "꧁༺RUBY༻꧂", category: "vip" },
  { id: "v26", text: "👑SAPPHIRE👑", category: "vip" },
  { id: "v27", text: "♛EMERALD♛", category: "vip" },
  { id: "v28", text: "『ᴷᴵᴺᴳ』JEWEL", category: "vip" },
  { id: "v29", text: "༺TREASURE༻", category: "vip" },
  { id: "v30", text: "꧁༺FORTUNE༻꧂", category: "vip" },
  { id: "v31", text: "👑WEALTH👑", category: "vip" },
  { id: "v32", text: "♛RICH♛", category: "vip" },
  { id: "v33", text: "『ᴷᴵᴺᴳ』BOSS", category: "vip" },
  { id: "v34", text: "༺CHIEF༻", category: "vip" },
  { id: "v35", text: "꧁༺MASTER༻꧂", category: "vip" },
  { id: "v36", text: "👑LEGEND👑", category: "vip" },
  { id: "v37", text: "♛ICON♛", category: "vip" },
  { id: "v38", text: "『ᴷᴵᴺᴳ』STAR", category: "vip" },
  { id: "v39", text: "༺HERO༻", category: "vip" },
  { id: "v40", text: "꧁༺CHAMPION༻꧂", category: "vip" },

  // Aesthetic Category (40 nicks)
  { id: "a1", text: "ᴀᴇsᴛʜᴇᴛɪᴄ", category: "aesthetic" },
  { id: "a2", text: "✧･ﾟ: *✧･ﾟ:*VIBE*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a3", text: "♡˚₊‧꒰აMOODა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a4", text: "༺ᴀᴜʀᴀ༻", category: "aesthetic" },
  { id: "a5", text: "꧁༺AURA༻꧂", category: "aesthetic" },
  { id: "a6", text: "✧･ﾟ: *✧･ﾟ:*GLOW*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a7", text: "♡˚₊‧꒰აSHINEა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a8", text: "༺ʀᴀᴅɪᴀɴᴄᴇ༻", category: "aesthetic" },
  { id: "a9", text: "꧁༺BLOOM༻꧂", category: "aesthetic" },
  { id: "a10", text: "✧･ﾟ: *✧･ﾟ:*BLOSSOM*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a11", text: "♡˚₊‧꒰აFLOWERა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a12", text: "༺ᴘᴇᴛᴀʟ༻", category: "aesthetic" },
  { id: "a13", text: "꧁༺GARDEN༻꧂", category: "aesthetic" },
  { id: "a14", text: "✧･ﾟ: *✧･ﾟ:*MEADOW*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a15", text: "♡˚₊‧꒰აFIELDა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a16", text: "༺ᴍɪsᴛ༻", category: "aesthetic" },
  { id: "a17", text: "꧁༺FOG༻꧂", category: "aesthetic" },
  { id: "a18", text: "✧･ﾟ: *✧･ﾟ:*HAZE*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a19", text: "♡˚₊‧꒰აDREAMა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a20", text: "༺ᴠɪsɪᴏɴ༻", category: "aesthetic" },
  { id: "a21", text: "꧁༺FANTASY༻꧂", category: "aesthetic" },
  { id: "a22", text: "✧･ﾟ: *✧･ﾟ:*MAGIC*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a23", text: "♡˚₊‧꒰აMYSTICა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a24", text: "༺ᴇɴᴄʜᴀɴᴛ༻", category: "aesthetic" },
  { id: "a25", text: "꧁༺SPELL༻꧂", category: "aesthetic" },
  { id: "a26", text: "✧･ﾟ: *✧･ﾟ:*CHARM*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a27", text: "♡˚₊‧꒰აGRACEა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a28", text: "༺ᴇʟᴇɢᴀɴᴄᴇ༻", category: "aesthetic" },
  { id: "a29", text: "꧁༺BEAUTY༻꧂", category: "aesthetic" },
  { id: "a30", text: "✧･ﾟ: *✧･ﾟ:*PRETTY*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a31", text: "♡˚₊‧꒰აLOVELYა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a32", text: "༺ᴅᴀʀʟɪɴɢ༻", category: "aesthetic" },
  { id: "a33", text: "꧁༺HONEY༻꧂", category: "aesthetic" },
  { id: "a34", text: "✧･ﾟ: *✧･ﾟ:*SUGAR*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a35", text: "♡˚₊‧꒰აSWEETა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a36", text: "༺ᴄᴀɴᴅʏ༻", category: "aesthetic" },
  { id: "a37", text: "꧁༺COTTON༻꧂", category: "aesthetic" },
  { id: "a38", text: "✧･ﾟ: *✧･ﾟ:*CLOUD*:･ﾟ✧*:･ﾟ✧", category: "aesthetic" },
  { id: "a39", text: "♡˚₊‧꒰აSKYა꒱ ‧₊˚♡", category: "aesthetic" },
  { id: "a40", text: "༺ʜᴇᴀᴠᴇɴ༻", category: "aesthetic" },
]
